server:
  http:
    host: ":8080"
  rpc:
    host: ":9000"
amqpclients:
  courses:
    host: "amqp://rabbitmq:secret@localhost:5672/"
database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: secret
  database: sumelms_course
